### ISSUE TITLE
Imagekit Android not working in production (ProGuard)

### ISSUE THREAD

**Issue by StamTsag** [imagekit-developer/imagekit-android#32]
**Describe the bug**
App crashes when I try to upload an image after successfully working without optimising for release.

**To Reproduce**
1. Test in dev that ImageKit works
2. Build for release
3. Watch it crash

**Expected behavior**
Work exactly like in dev

**Screenshots**
![image](https://github.com/imagekit-developer/imagekit-android/assets/78862561/f8d11112-d2be-4631-a565-569f78442225)
![image](https://github.com/imagekit-developer/imagekit-android/assets/78862561/2afb3e4c-21e8-41e2-854a-b903724895aa)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Version: 22

**Smartphone (please complete the following information):**
 - Device: Redmi 8
 - OS: Android 10
 - Browser: Brave
 - Version: 22

**Additional context**
Here's my proguard configuration:

```
-renamesourcefileattribute SourceFile

-dontwarn carbon.internal**
-dontwarn java.lang.invoke**

-dontwarn android.databinding.**
-keep class android.databinding.** { *; }
-keep class org.ocpsoft.prettytime.i18n.**
-keep class com.imagekit.android.**

# Disable logging in prod :)
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
    public static *** wtf(...);
    public static *** e(...);
}
```

**Comment by imagekitio** [comment]
Please check latest version 3.0.0

**Comment by StamTsag** [comment]
Same errors

![image](https://github.com/imagekit-developer/imagekit-android/assets/78862561/5ea4cf80-3c27-41dc-907b-1aee002c275e)

![image](https://github.com/imagekit-developer/imagekit-android/assets/78862561/ed7e0821-16b3-49b8-9a47-e1d9f0ec6461)

**Comment by StamTsag** [comment]
Also you shouldn't automate responses to issues, there is a reason they are issues

**Comment by plotic** [comment]
I have the same experience - only in release

**Comment by StamTsag** [comment]
Let's go, this feels like an abandoned project

**Comment by AniVerma17** [comment]
@Shadofer please provide the complete stack trace of the error

**Comment by StamTsag** [comment]
```2023-08-25 10:30:30.616  5481-5481  AndroidRuntime          com.fronvo                           E  FATAL EXCEPTION: main
Process: com.fronvo, PID: 5481
java.lang.IllegalArgumentException: Unable to create call adapter for class u6.h
for method a.a
at p3.a.x(Unknown Source:46)
at cb.v.b(Unknown Source:2682)
at d9.n.d(Unknown Source:30)
at cb.w0.invoke(Unknown Source:30)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy0.a(Unknown Source)
at z4.a.L(Unknown Source:151)
at q2.o2.call(Unknown Source:114)
at q2.e.onClick(Unknown Source:42)
at android.view.View.performClick(View.java:7125)
at android.view.View.performClickInternal(View.java:7102)
at android.view.View.access$3500(View.java:801)
at android.view.View$PerformClick.run(View.java:27336)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Caused by: java.lang.IllegalStateException: Single return type must be parameterized as Single<Foo> or Single<? extends Foo>
at db.i.a(Unknown Source:114)
at d9.n.a(Unknown Source:28)
at cb.v.b(Unknown Source:2517)
at d9.n.d(Unknown Source:30) 
at cb.w0.invoke(Unknown Source:30) 
at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
at $Proxy0.a(Unknown Source) 
at z4.a.L(Unknown Source:151) 
at q2.o2.call(Unknown Source:114) 
at q2.e.onClick(Unknown Source:42) 
at android.view.View.performClick(View.java:7125) 
at android.view.View.performClickInternal(View.java:7102) 
at android.view.View.access$3500(View.java:801) 
at android.view.View$PerformClick.run(View.java:27336) 
at android.os.Handler.handleCallback(Handler.java:883) 
at android.os.Handler.dispatchMessage(Handler.java:100) 
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:7356) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) ```

**Comment by florinleu** [comment]
Hi guys. We're experiencing the same issue on image upload. Can someone look into it?

**Comment by StamTsag** [comment]
We are becoming more!!
Imagekit should listen to its users

**Comment by StamTsag** [comment]
> Hi guys. We're experiencing the same issue on image upload. Can someone look into it?

AFAIK ProGuard is breaking some classes in ImageKit but it's their fault because be default nothing should be breaking so it's their ProGuard conf.

**Comment by StamTsag** [comment]
@imagekitio

**Comment by RolandNoTeamYet** [comment]
Hi guys, I have the same issue on release version of build. Compile SDK version is 33 (Android 13).

**Comment by AniVerma17** [comment]
Alright, so this is an issue with Retrofit and its RxJava adapter, when minified by R8 with full mode enabled (ref: https://github.com/square/retrofit/issues/3774).
I'll add the necessary keep rules to fix this issue ASAP

**Comment by StamTsag** [comment]
Is this fixed?

**Comment by imagekitio** [comment]
@Shadofer there is a mention of open PR in this ticket and an `in-progress` label attached. You can follow the PR and continue to follow this ticket for updates. Once this is fixed, we will update it here. 

Feel free to review the PR or add any constructive feedback to expedite the resolution. However I would request you to not create unnecessary noise here by following up frequently.

**Comment by imagekitio** [comment]
Fixed in version 3.0.1

**Comment by StamTsag** [comment]
Thanks

**Comment by JaleelNazir** [comment]
@StamTsag @imagekitio @AniVerma17 @plotic @florinleu 

Looks like this is not solved yet. It's happening for us. It would be helpful if we get any resolution. I have created a new issue for this.

https://github.com/imagekit-developer/imagekit-android/issues/37
